apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-udacity-app
  labels:
    app: my-udacity-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-udacity-app
  template:
    metadata:
      labels:
        app: my-udacity-app
    spec:
      containers:
      - name: udacity-simple-node
        image: slbenficaboy/udacity-simple-node
        ports:
        - containerPort: 80